export const siteConfig = {
  eventName: 'UmmahHacks',
  date: 'January 24-25, 2026',
  location: 'Waterloo, Ontario',
  applicationLink: '#apply',
  lumaLink: 'https://luma.com/otrho3gh',
  discordLink: 'https://discord.gg/ummahhacks',
  sponsorLink: 'https://form.typeform.com/to/KiQRV7qW',
  email: 'muhibwaqar@hotmail.com',
  socials: {
    twitter: 'https://twitter.com/ummahhacks',
    instagram: 'https://instagram.com/ummahhacks',
    linkedin: 'https://linkedin.com/company/ummahhacks',
  },
  stats: {
    hackers: '100-200',
    duration: '36 hours',
    prizes: 'To be announced soon',
  },
  tracks: [
    {
      id: 'civic-tech',
      name: 'Civic Tech',
      icon: 'Building2',
      description: 'Build solutions that improve civic engagement and government services.',
    },
    {
      id: 'health',
      name: 'Health & Wellness',
      icon: 'Heart',
      description: 'Create tools to improve healthcare access and wellness in our communities.',
    },
    {
      id: 'climate',
      name: 'Climate & Environment',
      icon: 'Leaf',
      description: 'Develop innovations to address climate change and environmental challenges.',
    },
    {
      id: 'fintech',
      name: 'FinTech',
      icon: 'Wallet',
      description: 'Build ethical financial solutions that serve underserved communities.',
    },
    {
      id: 'ai-good',
      name: 'AI for Good',
      icon: 'Brain',
      description: 'Leverage AI to solve real-world problems and create positive impact.',
      beginnerFriendly: true,
    },
    {
      id: 'education',
      name: 'Education',
      icon: 'GraduationCap',
      description: 'Create learning tools and platforms that make education more accessible.',
    },
  ],
  speakers: [
    { 
      name: 'Yasin Ehsan', 
      role: 'Speaker/Judge', 
      company: '', 
      avatar: '/speakers/YASINLKDN.jpeg',
      linkedin: 'https://www.linkedin.com/in/yasinehsan/',
    },
    { 
      name: 'Rana Zaky', 
      role: 'Speaker/Judge', 
      company: '', 
      avatar: '/speakers/RANALKDN.jpeg',
      linkedin: 'https://www.linkedin.com/in/rana-zaky/',
    },
    { 
      name: 'Nabeeha Ahmed', 
      role: 'Speaker/Judge', 
      company: 'Microsoft', 
      avatar: '/speakers/Nabeeha.jpeg',
      linkedin: 'https://www.linkedin.com/in/nabeeha-ahmed/',
    },
    { 
      name: 'Shaden Awad', 
      role: 'Speaker/Judge', 
      company: '', 
      avatar: '/speakers/Shaden.jpeg',
      linkedin: 'https://www.linkedin.com/in/shaden-awad-a45b421b6/',
    },
    { 
      name: 'Tabassum Pasha', 
      role: 'Speaker/Judge', 
      company: '', 
      avatar: '/speakers/Tabassum.jpeg',
      linkedin: 'https://www.linkedin.com/in/tabassum-pasha/',
    },
    { 
      name: 'Ali Khani', 
      role: 'Speaker/Judge', 
      company: '', 
      avatar: '/speakers/Ali.jpeg',
      linkedin: 'https://www.linkedin.com/in/khvni/',
    },
    { 
      name: 'Safi Qadir', 
      role: 'Speaker/Judge', 
      company: '', 
      avatar: '/speakers/Safi.jpeg',
      linkedin: 'https://www.linkedin.com/in/safizaq/',
    },
  ],
  schedule: {
    day1: [
      {
        day: 'Friday, January 24',
        time: '9:00 AM',
        title: 'Opening Ceremony',
        description: 'Welcome & vision • Hackathon rules • Tracks & judging overview',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '10:00 AM',
        title: 'Ideation & Team Formation',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '12:30 PM',
        title: 'Dhuhr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '1:30 PM',
        title: 'Hacking Begins',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '3:30 PM',
        title: 'Asr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '4:00 PM',
        title: 'Workshop / Mentor Hours',
        description: 'Design thinking • Ethical tech & impact',
        type: 'workshop' as const,
      },
      {
        day: 'Friday, January 24',
        time: '6:00 PM',
        title: 'Maghrib Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '6:30 PM',
        title: 'Dinner',
        description: 'Halal & vegetarian',
        type: 'meal' as const,
      },
      {
        day: 'Friday, January 24',
        time: '7:30 PM',
        title: 'Hacking Continues',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '8:00 PM',
        title: 'Isha Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '9:00 PM',
        title: 'Night Productivity Block',
        description: 'Quiet zones • Mentor support',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '11:30 PM',
        title: 'Midnight Snack',
        description: '',
        type: 'meal' as const,
      },
    ],
    day2: [
      {
        day: 'Friday, January 24',
        time: '5:45 AM',
        title: 'Fajr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '6:30 AM',
        title: 'Rest / Quiet Work Block',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '9:00 AM',
        title: 'Breakfast',
        description: '',
        type: 'meal' as const,
      },
      {
        day: 'Friday, January 24',
        time: '10:00 AM',
        title: 'Mentor Review Sessions',
        description: 'Pitch feedback • UX/UI review',
        type: 'workshop' as const,
      },
      {
        day: 'Friday, January 24',
        time: '12:30 PM',
        title: 'Dhuhr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '1:30 PM',
        title: 'Final Hacking Sprint',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '3:30 PM',
        title: 'Asr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '4:30 PM',
        title: 'Submissions Due',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '5:45 PM',
        title: 'Maghrib Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '6:15 PM',
        title: 'Final Presentations & Judging',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '8:00 PM',
        title: 'Isha Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '9:00 PM',
        title: 'Closing Ceremony & Awards',
        description: 'Event ends — 36 hours complete',
        type: 'main' as const,
      },
    ],
  },
  hackathonTracks: [
    {
      id: 'social-impact',
      title: 'Social Impact',
      purpose: 'Global and local impact, social good, and community development.',
      challenge: 'Develop tech solutions that address real-world issues within the Muslim Ummah, bridging the gap between global needs (refugee aid, disaster relief, justice for suffering countries) and local community challenges (mosque engagement, food insecurity).',
      icon: 'Heart',
    },
    {
      id: 'halal-fintech',
      title: 'Halal FinTech & Ethical Economy',
      purpose: 'Halal finance, ethical investing, and Islam-compliant business tools.',
      challenge: 'Create FinTech solutions that make Islamic finance principles (such as avoidance of Riba, transparency, and ethical investment) more accessible, efficient, and innovative for modern users and businesses.',
      icon: 'Wallet',
    },
    {
      id: 'open-innovation',
      title: 'Open Innovation',
      purpose: 'Encourage creativity, strategic thinking, and user-centered innovation by focusing on ideation, design, and feasibility rather than implementation.',
      challenge: 'Teams must fully conceptualize, design, and create the blueprint and pitch for an innovative solution without writing a single line of code. This emphasizes Design Thinking, User Experience (UX/UI), Market Research, and Business Strategy.',
      icon: 'Lightbulb',
    },
  ],
  faq: [
    {
      question: 'Who can participate?',
      answer: 'UmmahHacks is open to all students and professionals interested in building solutions for community impact. No prior experience required!',
    },
    {
      question: 'What is the team size?',
      answer: 'Teams can have 2-4 members. You can register as a team or find teammates at the event.',
    },
    {
      question: 'Is there a registration fee?',
      answer: 'No, UmmahHacks is completely free to attend. Food, drinks, and swag are all included!',
    },
    {
      question: 'Will food be provided?',
      answer: 'Yes! We provide all meals, snacks, and beverages throughout the event. Dietary accommodations including halal and vegetarian options are available.',
    },
    {
      question: 'Is there a prayer space?',
      answer: 'Yes, we have a dedicated quiet space available for prayers and reflection throughout the event.',
    },
    {
      question: 'What should I bring?',
      answer: 'Bring your laptop, charger, and any other tools you need to code. We\'ll provide the rest!',
    },
    {
      question: 'Do I need to have an idea before the event?',
      answer: 'Not at all! You can come with an idea or brainstorm with your team at the hackathon.',
    },
    {
      question: 'What is the code of conduct?',
      answer: 'UmmahHacks is committed to providing a safe, inclusive, and respectful environment for all participants. Please review our Code of Conduct for details.',
    },
    {
      question: 'Can I work on a project I started before?',
      answer: 'No, all projects must be started during the hackathon. However, you can use libraries, frameworks, and APIs that existed before the event.',
    },
    {
      question: 'How will projects be judged?',
      answer: 'Projects will be evaluated based on innovation, technical execution, impact potential, and presentation quality.',
    },
  ],
  sponsors: [
    {
      name: 'VePay',
      logo: '/sponsors/vepay.jpg',
      tier: 'tier1',
      url: 'https://vepay.io/',
      description: 'Shariah Compliant Funding for eCommerce Sellers',
    },
    {
      name: 'Ummah1',
      logo: '/sponsors/ummah_1.jpg',
      tier: 'tier1',
      url: 'https://ummah1.com',
      description: 'Ummah1 is a platform for empowering startups, fueling growth from seed to success. ',
    },
    {
      name: 'Automax AI',
      logo: '/sponsors/automax_ai.jpg',
      tier: 'tier1',
      url: 'https://automax.ai/',
      description: 'Automax AI is building AI for better transparency and accuracy in property valuations ',
    },
    {
      name: 'Insforge',
      logo: '/sponsors/insforge_logo.jpg',
      tier: 'tier2',
      url: 'https://insforge.dev/',
      description: 'Insforge is building the first backend for AI agents',
    },
    {
      name: 'Breakthrough Ventures',
      logo: '/sponsors/breakthrough_ventures.jpg',
      tier: 'tier3',
      url: 'breakvc.com',
      description: 'Breakthrough Ventures is a venture capital firm that invests in early-stage student-led startups',
    },
    {
      name: 'ASL Aspire',
      logo: '/sponsors/asl_aspire_logo.jpg',
      tier: 'tier3',
      url: 'https://aslaspire.com/',
      description:" ASL Aspire is an online educational platform that teaches STEM literacy to deaf students and their teachers."
    },
    {
      name: 'Amano',
      logo: '/sponsors/amano.jpg',
      tier: 'tier3',
      url: 'https://amanolabs.com',
      description: "Amano designs pratical solutions for neurological technologies"
    },
    {
      name:"Hex Security",
      logo: '/sponsors/hex_security_logo.jpg',
      tier: 'tier3',
      url: 'https://hex.co',
      description: "Peneration testing using autonomus AI agents"
    }
  ],
}
