export const siteConfig = {
  eventName: 'UmmahHacks',
  date: 'March 15-16, 2024',
  location: 'Toronto, Canada',
  applicationLink: '#apply',
  lumaLink: 'https://luma.com/otrho3gh',
  discordLink: 'https://discord.gg/ummahhacks',
  email: 'hello@ummahhacks.com',
  socials: {
    twitter: 'https://twitter.com/ummahhacks',
    instagram: 'https://instagram.com/ummahhacks',
    linkedin: 'https://linkedin.com/company/ummahhacks',
  },
  stats: {
    hackers: '100-200',
    duration: '36 hours',
    prizes: 'To be announced soon',
  },
  tracks: [
    {
      id: 'civic-tech',
      name: 'Civic Tech',
      icon: 'Building2',
      description: 'Build solutions that improve civic engagement and government services.',
    },
    {
      id: 'health',
      name: 'Health & Wellness',
      icon: 'Heart',
      description: 'Create tools to improve healthcare access and wellness in our communities.',
    },
    {
      id: 'climate',
      name: 'Climate & Environment',
      icon: 'Leaf',
      description: 'Develop innovations to address climate change and environmental challenges.',
    },
    {
      id: 'fintech',
      name: 'FinTech',
      icon: 'Wallet',
      description: 'Build ethical financial solutions that serve underserved communities.',
    },
    {
      id: 'ai-good',
      name: 'AI for Good',
      icon: 'Brain',
      description: 'Leverage AI to solve real-world problems and create positive impact.',
      beginnerFriendly: true,
    },
    {
      id: 'education',
      name: 'Education',
      icon: 'GraduationCap',
      description: 'Create learning tools and platforms that make education more accessible.',
    },
  ],
  schedule: {
    day1: [
      {
        day: 'Friday, January 24',
        time: '9:00 AM',
        title: 'Opening Ceremony',
        description: 'Welcome & vision • Hackathon rules • Tracks & judging overview',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '10:00 AM',
        title: 'Ideation & Team Formation',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '12:30 PM',
        title: 'Dhuhr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '1:30 PM',
        title: 'Hacking Begins',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '3:30 PM',
        title: 'Asr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '4:00 PM',
        title: 'Workshop / Mentor Hours',
        description: 'Design thinking • Ethical tech & impact',
        type: 'workshop' as const,
      },
      {
        day: 'Friday, January 24',
        time: '6:00 PM',
        title: 'Maghrib Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '6:30 PM',
        title: 'Dinner',
        description: 'Halal & vegetarian',
        type: 'meal' as const,
      },
      {
        day: 'Friday, January 24',
        time: '7:30 PM',
        title: 'Hacking Continues',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '8:00 PM',
        title: 'Isha Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '9:00 PM',
        title: 'Night Productivity Block',
        description: 'Quiet zones • Mentor support',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '11:30 PM',
        title: 'Midnight Snack',
        description: '',
        type: 'meal' as const,
      },
    ],
    day2: [
      {
        day: 'Friday, January 24',
        time: '5:45 AM',
        title: 'Fajr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '6:30 AM',
        title: 'Rest / Quiet Work Block',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '9:00 AM',
        title: 'Breakfast',
        description: '',
        type: 'meal' as const,
      },
      {
        day: 'Friday, January 24',
        time: '10:00 AM',
        title: 'Mentor Review Sessions',
        description: 'Pitch feedback • UX/UI review',
        type: 'workshop' as const,
      },
      {
        day: 'Friday, January 24',
        time: '12:30 PM',
        title: 'Dhuhr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '1:30 PM',
        title: 'Final Hacking Sprint',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '3:30 PM',
        title: 'Asr Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '4:30 PM',
        title: 'Submissions Due',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '5:45 PM',
        title: 'Maghrib Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '6:15 PM',
        title: 'Final Presentations & Judging',
        description: '',
        type: 'main' as const,
      },
      {
        day: 'Friday, January 24',
        time: '8:00 PM',
        title: 'Isha Prayer Break',
        description: '',
        type: 'prayer' as const,
      },
      {
        day: 'Friday, January 24',
        time: '9:00 PM',
        title: 'Closing Ceremony & Awards',
        description: 'Event ends — 36 hours complete',
        type: 'main' as const,
      },
    ],
  },
  hackathonTracks: [
    {
      id: 'social-impact',
      title: 'Social Impact',
      purpose: 'Global and local impact, social good, and community development.',
      challenge: 'Develop tech solutions that address real-world issues within the Muslim Ummah, bridging the gap between global needs (refugee aid, disaster relief, justice for suffering countries) and local community challenges (mosque engagement, food insecurity).',
      icon: 'Heart',
    },
    {
      id: 'halal-fintech',
      title: 'Halal FinTech & Ethical Economy',
      purpose: 'Halal finance, ethical investing, and Islam-compliant business tools.',
      challenge: 'Create FinTech solutions that make Islamic finance principles (such as avoidance of Riba, transparency, and ethical investment) more accessible, efficient, and innovative for modern users and businesses.',
      icon: 'Wallet',
    },
    {
      id: 'open-innovation',
      title: 'Open Innovation',
      purpose: 'Encourage creativity, strategic thinking, and user-centered innovation by focusing on ideation, design, and feasibility rather than implementation.',
      challenge: 'Teams must fully conceptualize, design, and create the blueprint and pitch for an innovative solution without writing a single line of code. This emphasizes Design Thinking, User Experience (UX/UI), Market Research, and Business Strategy.',
      icon: 'Lightbulb',
    },
  ],
  faq: [
    {
      question: 'Who can participate?',
      answer: 'UmmahHacks is open to all students and professionals interested in building solutions for community impact. No prior experience required!',
    },
    {
      question: 'What is the team size?',
      answer: 'Teams can have 2-4 members. You can register as a team or find teammates at the event.',
    },
    {
      question: 'Is there a registration fee?',
      answer: 'No, UmmahHacks is completely free to attend. Food, drinks, and swag are all included!',
    },
    {
      question: 'Will food be provided?',
      answer: 'Yes! We provide all meals, snacks, and beverages throughout the event. Dietary accommodations including halal and vegetarian options are available.',
    },
    {
      question: 'Is there a prayer space?',
      answer: 'Yes, we have a dedicated quiet space available for prayers and reflection throughout the event.',
    },
    {
      question: 'What should I bring?',
      answer: 'Bring your laptop, charger, and any other tools you need to code. We\'ll provide the rest!',
    },
    {
      question: 'Do I need to have an idea before the event?',
      answer: 'Not at all! You can come with an idea or brainstorm with your team at the hackathon.',
    },
    {
      question: 'What is the code of conduct?',
      answer: 'UmmahHacks is committed to providing a safe, inclusive, and respectful environment for all participants. Please review our Code of Conduct for details.',
    },
    {
      question: 'Can I work on a project I started before?',
      answer: 'No, all projects must be started during the hackathon. However, you can use libraries, frameworks, and APIs that existed before the event.',
    },
    {
      question: 'How will projects be judged?',
      answer: 'Projects will be evaluated based on innovation, technical execution, impact potential, and presentation quality.',
    },
  ],
  sponsors: [
    { name: 'TechCorp', logo: '🏢' },
    { name: 'InnovateLab', logo: '🔬' },
    { name: 'StartupHub', logo: '🚀' },
    { name: 'CodeForGood', logo: '💻' },
    { name: 'FutureVentures', logo: '🌟' },
  ],
}
